version: '3.1'

volumes:
  db-data:
    external: false

services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'supersecret'
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - 33060:3306
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis
    ports:
      - 63790:6379
